require 'skill.英雄技能.天楼闪薙斩'
require 'skill.英雄技能.卧龙光线'
require 'skill.英雄技能.破灭紫电'
require 'skill.英雄技能.五月雨斩'
require 'skill.英雄技能.鬼神乱舞'
require 'skill.英雄技能.动地跺'
require 'skill.英雄技能.武神枪'
require 'skill.英雄技能.射手天箭'